"""empty message

Revision ID: c786d27a9c5f
Revises: cf3ab8202674
Create Date: 2020-11-19 17:06:45.766343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c786d27a9c5f'
down_revision = 'cf3ab8202674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shipment', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'customer_id')
    # ### end Alembic commands ###
